name: Python application chrom

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Print current directory
      run: pwd
    - name: Install dependencies
      run: python3 -m pip install --upgrade pip
    - name: Install requirements
      run: pip install -r src/requirements.txt
    - name: Install Chrome and ChromeDriver
      run: |
          CHROMEDRIVER_VERSION="126.0.6478.126"
          mkdir chromedriver
          cd chromedriver
          wget https://storage.googleapis.com/chrome-for-testing-public/$CHROMEDRIVER_VERSION/linux64/chrome-headless-shell-linux64.zip
          unzip chrome-headless-shell-linux64.zip -d ./ 
          cd ../
          sudo mv chromedriver /usr/local/bin/
          sudo chown root:root /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb
          sudo apt-get install -f
          rm -rf chromedriver
    - name: Run tests with ChromeDriver
      env:
        CHROME_WEBDRIVER: '/usr/bin/chromedriver'
        CHROMEDRIVER_CHROME_PATH: '/usr/bin/google-chrome-stable'
      run: |
        # 在这里添加使用ChromeDriver的测试运行命令
        # 例如：pytest -v --browser-name=chrome src/test.py
        # 注意：确保你的测试脚本能够读取到环境变量
    - name: Test with pytest
      run: |
        python src/test.py
    - name: Commit and Push files
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@users.noreply.github.com"
          git add .
          git commit -m "Add itvlist.txt to src directory"
          git push
